### ISSUE TITLE
INSTALL.TXT is outdated

### ISSUE THREAD

**Issue by corbett3000** [localprojects/Change-By-Us#1]
I appears the links to install guides all result in 404 errors: https://github.com/localprojects/Change-By-Us/blob/master/INSTALL.txt

Perhaps you intended to link to  https://github.com/localprojects/Change-By-Us/wiki rather than Code for America wiki entries?

**Comment by ayen** [comment]
Thank you for catching that--all fixed!

**Comment by corbett3000** [comment]
My pleasure :)
