### ISSUE TITLE
lighttpd.conf: Fast CGI Settings

### ISSUE THREAD

**Issue by cvee** [localprojects/Change-By-Us#16]
In lighttpd.conf.sample, the Fast CGI section appears as follows:

```
# Fast CGI settings
#--------------------------------------------------------------------
# Settings for Fast CGI.
#
#--------------------------------------------------------------------
fastcgi.server = ("/main.py" =>
    ((  "socket" => "/tmp/fastcgi.socket",
        "bin-path" => var.binpath,
        "max-procs" => 1,
        "bin-environment" => (
            "REAL_SCRIPT_NAME" => ""
        ),
        "check-local" => "disable"
    ))
)
```

The Installation Instructions (Ubuntu) do not provide clear instructions about what values need to be set. Is REAL_SCRIPT_NAME supposed to be replaced by a value? If so, what value should be provided?

**Comment by cybertoast** [comment]
Only the python interpolated variables need to be set. The other settings
can be left as they are.
For more information, see http://webpy.org/cookbook/fastcgi-lighttpd

On Wed, Jan 4, 2012 at 4:36 PM, Chris Verwymeren <
reply@reply.github.com
