### ISSUE TITLE
"Sign In with Facebook" JavaScript error

### ISSUE THREAD

**Issue by cvee** [localprojects/Change-By-Us#18]
On a fresh install of CBU, attempting to sign in with Facebook results in the following JavaScript error on line 23 of all.js:

```
Error: OAuth2 specification states that 'perms' should now be called 'scope'.  Please update.
```

**Comment by cybertoast** [comment]
Just committed a patch to the develop branch. Please could you pull from
develop and see if this works for you. I'll be testing on my side as well
and will commit to master once it looks stable.
Thanks much.

On Thu, Jan 5, 2012 at 1:17 PM, Chris Verwymeren <
reply@reply.github.com

**Comment by cvee** [comment]
Switched to the develop branch. The Facebook authentication window now pops up.
