### ISSUE TITLE
Cannot create configuration file and run locally

### ISSUE THREAD

**Issue by phillipsj** [localprojects/Change-By-Us#26]
The installation instructions are not complete and I cannot get a copy of this application running locally on my dev box.  I have followed all comments, issues, etc. trying to get this application to work.  Can more complete documentation be created.

**Comment by ethanholda** [comment]
Hi there.  Can you please provide more detail about the specific issue(s) you are having?

**Comment by phillipsj** [comment]
I have am using Ubuntu Linux.  If I follow the installation instructions for Ubuntu on the Wiki, I do not have an working application.  The config.yaml file is misconfigured, I did a little digging on the github and found that I need to use Fabric to generate my config.yaml using an rcfile.  However, I keep receiving this error when running the following fabric command:

﻿$ fab --config=rcfile create_config_yaml

Fatal error: Command(s) not found:
    create_config_yaml

Aborting.

$

-----Original Message-----

**Comment by phillipsj** [comment]
Any one here that can help?  We would really like to use this application, but I am not having much luck configuring a development environment.

**Comment by ethanholda** [comment]
Hi Phillip.  Sorry this issue slid out of focus.  We have someone working on getting out more complete instructions.

**Comment by phillipsj** [comment]
Thanks

**Comment by houndbee** [comment]
Any progress on this?

**Comment by cybertoast** [comment]
`create_config_yaml` is not a valid fabric task. To create a local configuration file:
- Copy and alter rcfile.sample as appropriate, to (for example) my.rcfile
- Run `fab -c my.rcfile dev bundle_code create_local_configs`

This will interpolate the etc/config.yaml file with variables in my.rcfile. The output will to the "build_path" as defined in your rcfile (generally /tmp/change-by-us/releases or something similar).

The documentation could definitely use an update. But please let me know if this works and I'll start making the changes.

**Comment by simon-mcc** [comment]
hi all, actually i have the same kind of problem.
I follow the ubuntu how-to.
I'm working on a AWS server.

i don't really understand how to customize (and use) the config.yaml file

thx

**Comment by cybertoast** [comment]
simon-mcc, were you able to move forward with the config?
