### ISSUE TITLE
Installation Instructions (Mac and Ubuntu) - Application Configuration section contains outdated instructions 

### ISSUE THREAD

**Issue by cvee** [localprojects/Change-By-Us#3]
The Application Configuration section contains the following instructions:

**Application**
1. Copy the sample config.yaml.sample file to config.yaml
   - cp config.yaml.sample config.yaml
2. Edit config.yaml with appropriate values.

config.yaml.sample cannot be found in the project root. Has the file been moved to an alternate location or removed completely?

**Comment by localprojects** [comment]
cvee, seems like some of our installation steps are a bit broken during our final push to github. I'll go through the process and update the code and wiki. Thanks much for noticing and reporting. And sorry for the inconvenience.

**Comment by localprojects** [comment]
cvee,
The configuration template is at etc/config.yaml.tmpl. This is the file that must be copied, modified and saved as config.yaml. Hope this helps.
