### ISSUE TITLE
Incorrect config.yaml file path in frameworks/config.py

### ISSUE THREAD

**Issue by cvee** [localprojects/Change-By-Us#5]
The file path for loading config.yaml is incorrect resulting in the following error:

```
IOError: [Errno 2] No such file or directory
```

**Comment by cybertoast** [comment]
Thanks cvee, and sorry for the delay in response. I've been out of inet access. I've made the merge but am not completely sure it is correct in retrospect. I'll think about it some more and post here if I revert the merge (and provide updated info also).

**Comment by cybertoast** [comment]
Reverted the merge - see the pull acceptance notes for more explanation: https://github.com/localprojects/Change-By-Us/pull/6
